baseURL = "https://piers.dev"
languageCode = "en-us"
title = "piers.dev"
theme = "anatole"
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
title = "piers.dev"
author = "Piers Karsenbarg"
profilePicture = "images/profile.jpg"
customCss = ["css/syntax.css"]

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/pierskarsenbarg"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/pierskarsenbarg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "linkedin"
url = "https://www.linkedin.com/in/piers-karsenbarg"

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "About"
identifier = "about"
weight = 200
url = "/about"
